### ISSUE TITLE
Fade out and mute not working with flac task

### ISSUE THREAD

**Issue by luar123** [CarlosDerSeher/snapclient#23]
The fade out feature (and also mute) are not working anymore because the value of flow_drain_counter is not send to the flac task. Not sure what's the best way to send it there, maybe a queue or a global variable?

**Comment by CarlosDerSeher** [comment]
maybe through player_get_snapcast_settings() and player_set_snapcast_settings() ?

**Comment by luar123** [comment]
Thanks for the hint. Was easier to fix than I thought initially.

**Comment by luar123** [comment]
Fade-out removed for now and mute fixed.
