### ISSUE TITLE
Build fails with ethernet disabled

### ISSUE THREAD

**Issue by luar123** [CarlosDerSeher/snapclient#24]
Build fails with ethernet disabled:
```
.../esp/snapclient/components/eth_interface/eth_interface.c: In function 'eth_init':
.../esp/snapclient/components/eth_interface/eth_interface.c:100:25: error: 'CONFIG_SNAPCLIENT_ETH_PHY_ADDR' undeclared (first use in this function); did you mean 'CONFIG_SNAPCLIENT_NAME'?
   phy_config.phy_addr = CONFIG_SNAPCLIENT_ETH_PHY_ADDR;
```
eth_interface.c should probably not be included at all.

**Comment by CarlosDerSeher** [comment]
Yes I realized that already. Can this be excluded through cmake? I repaired that locally already but didn't have time to push yet

**Comment by CarlosDerSeher** [comment]
Ok, found the answer myself.

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html#adding-conditional-configuration
