### ISSUE TITLE
Stereo with a bluetooth speaker

### ISSUE THREAD

**Issue by kyvaith** [CarlosDerSeher/snapclient#31]
Hi, is it possible to have a wired speaker attached to the board, and at the same time bluetooth speaker connected to make them both work in stereo?

**Comment by CarlosDerSeher** [comment]
No as Bluetooth connection isn't implemented. Also you will never be able to exactly sync  both of them. Bluetooth has high latency compared to the cable. You could theoretically measure this latency, probably a lot of effort. Not worth the trouble in my opinion.
