### ISSUE TITLE
compile errors on fresh installed idf 5.0.2

### ISSUE THREAD

**Issue by rcmcronny** [CarlosDerSeher/snapclient#34]
I tried with the develop branch, as i wanted to test it with my esp audio module 2.2 (which should be similar to the lyrat).

[idf_py_stdout_output_12287.txt](https://github.com/CarlosDerSeher/snapclient/files/11581711/idf_py_stdout_output_12287.txt)

I am not that programmer with idf  ans so  somewhat helpless, is that because of a new  idf ?

Thanks,
Ronny

**Comment by CarlosDerSeher** [comment]
Porting to IDF 5 is on my to do list but if you checkout the README there you'll find it will only compile using ESP-IDF v4.3.1
