### ISSUE TITLE
Connection isn't working when using static IP

### ISSUE THREAD

**Issue by Aragur** [CarlosDerSeher/snapclient#5]
When using this fork my ESP32 cannot connect to the Snapcast Server.
```SC: can't connect to remote 192.168.178.51:1704, err -13```
Using mDNS is working fine.

**Comment by CarlosDerSeher** [comment]
We'll see, this doesn't have much priority for me, as I don't have much use for the static IP option. I think it has to do with the IP format being somehow incorrect. You are welcome to try repairing this.

**Comment by CarlosDerSeher** [comment]
issue should be resolved in master.
