### ISSUE TITLE
How to use different Board?

### ISSUE THREAD

**Issue by DerPicknicker** [CarlosDerSeher/snapclient#50]
Hello, 

I have some nice boards laying around. Here: https://www.tindie.com/products/sonocotta/louder-esp32/

But I am not happy with LMS and the overall performance. So I want to give Snapcast a try. 

Would it be a lot of work to support different boards like these? 

It has PSRAM onboard and also an I2S amplifier. https://www.ti.com/product/TAS5805M

This amp needs i2c commands to get running. I can provide them if you say me where I have to put them. Currently I doesn't have an IDF 4 version installed. So I can't build it right now. Are these changes possible after building or they are "hard-coded"?

Thank you for the work you already did.

**Comment by CarlosDerSeher** [comment]
Please see #36 and #27

You will need to write the driver for DAC in question.

**Comment by DerPicknicker** [comment]
@CarlosDerSeher .. 

Thank you. I will see what I can do. 

Currently all my projects are IDF5 and for me it would take a lot of time to re-install the idf4. If I prepare all things on my side (the driver etc...) would you be so kind and test if it's compiling?

Best regards

**Comment by CarlosDerSeher** [comment]
From my experience it is not that much of a hassle to switch between versions. Have a look at https://github.com/espressif/idf-eclipse-plugin

**Comment by DerPicknicker** [comment]
@CarlosDerSeher ...

I will see what I can achieve on my side. I just looked into the code. Should I create an audio_board or an custom_board? 


The amp needs i2c commands for setting it up and uses for audio a simple i2s stream.

**Comment by CarlosDerSeher** [comment]
Please see https://github.com/CarlosDerSeher/snapclient/issues/36#issuecomment-1709095715

**Comment by DerPicknicker** [comment]
@CarlosDerSeher ... I will do my best. It will take time. This is another thing on my list 😅... 

There is also an Arduino implementation of Snapcast I will check that out if this supports my Dac. My sparetime is decreasing faster and faster with much more side-projects 😂

I will try to do it this year. Lets see.

**Comment by DerPicknicker** [comment]
Hi @CarlosDerSeher .. 

I started working on the new Board. Is there a way that I can create a template for that specific board? The Board has some PSRAM installed or I have to change it manually and the Driver is just focussed on the I2S DAC?

Thank you in Advance

**Comment by CarlosDerSeher** [comment]
Do you mean a default sdkconfig? For now I just add a template sdkconfig to the repository like so: [sdkconfig_adau1961](https://github.com/CarlosDerSeher/snapclient/blob/master/sdkconfig_adau1961)

Currently there is no real way to add a custom board like it is done in [audio_board](https://github.com/CarlosDerSeher/snapclient/tree/master/components/audio_board), there is only the generic board which focuses on the DAC part. What you could do is to add an entry in [Kconfig.projbuild](https://github.com/CarlosDerSeher/snapclient/blob/master/components/custom_board/Kconfig.projbuild) where the user can enable/disable PSRAM directly and doesn't have to walk the menu for that.

**Comment by DerPicknicker** [comment]
> Also you could always add the board to [audio_board](https://github.com/CarlosDerSeher/snapclient/tree/master/components/audio_board) I guess, ADF is probably also a good reference on how to do that.

Just for my Understanding before adding an audio_board. I have to write a driver, right? In that audio_board I use the Driver for my I2S DAC?

**Comment by CarlosDerSeher** [comment]
Yes, the DAC drivers not supplied by ADF are located in [custom_board](https://github.com/CarlosDerSeher/snapclient/tree/master/components/custom_board). Check out one of the existing drivers like [adau1961](https://github.com/CarlosDerSeher/snapclient/tree/master/components/custom_board/adau1961) to see how it is done. Just copy one of the drivers and replace with your I2C init code. That part is a bit of a mess because it would be much cleaner if all was put  to [audio_hal](https://github.com/CarlosDerSeher/snapclient/tree/master/components/audio_hal) but then the copied parts from ADF would be mixed up with the parts added by us. I am planing on throwing out the ADF copied code completly at some point and try to just link to needed files from ADF through CMakeLists.txt, but as you already said it spare time is a scrace thing.

Good luck coding

**Comment by CarlosDerSeher** [comment]
please create a seperate branch for that.

**Comment by CarlosDerSeher** [comment]
Please open a discussion on that topic

**Comment by cguedel** [comment]
@DerPicknicker did you ever get that louder esp32 board working?

**Comment by DerPicknicker** [comment]
@cguedel .. yes it works fine. Flash it with the provided web installer [see here](https://sonocotta.github.io/esparagus-snapclient/)
