### ISSUE TITLE
Lyrat 4.2 fail to build 

### ISSUE THREAD

**Issue by SantiagoSotoC** [CarlosDerSeher/snapclient#61]
I selected the Lyrat 4.2 option which should be supported and it fails to compile, I am using linux and I run ESP-IDF in docker as documented. 

`Your environment is not configured to handle unicode filenames outside of ASCII range. Environment variable LC_ALL is temporary set to C.UTF-8 for unicode support.
Executing action: all (aliases: build)
Running ninja in directory /project/build
Executing "ninja all"...
[1/800] Performing build step for 'bootloader'
ninja: no work to do.
[4/798] Building C object esp-idf/audio_hal/CMakeFiles/__idf_audio_hal.dir/driver/es8388/headphone_detect.c.obj
FAILED: esp-idf/audio_hal/CMakeFiles/__idf_audio_hal.dir/driver/es8388/headphone_detect.c.obj 
ccache /opt/esp/tools/xtensa-esp32-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -Iconfig -I../components/audio_hal/include -I../components/audio_hal/driver/es8388 -I../components/audio_hal/driver/es8374 -I../components/audio_hal/driver/es8311 -I../components/audio_hal/driver/es7243 -I../components/audio_hal/driver/es7148 -I../components/audio_hal/driver/es7210 -I../components/audio_hal/driver/tas5805m -I../components/audio_hal/driver/include -I/opt/esp/idf/components/newlib/platform_include -I/opt/esp/idf/components/freertos/include -I/opt/esp/idf/components/freertos/include/esp_additions -I/opt/esp/idf/components/freertos/port/xtensa/include -I/opt/esp/idf/components/esp_hw_support/include -I/opt/esp/idf/components/esp_hw_support/port/esp32/. -I/opt/esp/idf/components/esp_hw_support/port/esp32/private_include -I/opt/esp/idf/components/heap/include -I/opt/esp/idf/components/log/include -I/opt/esp/idf/components/lwip/include/apps -I/opt/esp/idf/components/lwip/include/apps/sntp -I/opt/esp/idf/components/lwip/lwip/src/include -I/opt/esp/idf/components/lwip/port/esp32/include -I/opt/esp/idf/components/lwip/port/esp32/include/arch -I/opt/esp/idf/components/soc/include -I/opt/esp/idf/components/soc/esp32/. -I/opt/esp/idf/components/soc/esp32/include -I/opt/esp/idf/components/hal/esp32/include -I/opt/esp/idf/components/hal/include -I/opt/esp/idf/components/esp_rom/include -I/opt/esp/idf/components/esp_rom/esp32 -I/opt/esp/idf/components/esp_rom/include/esp32 -I/opt/esp/idf/components/esp_common/include -I/opt/esp/idf/components/esp_system/include -I/opt/esp/idf/components/esp32/include -I/opt/esp/idf/components/driver/include -I/opt/esp/idf/components/driver/esp32/include -I/opt/esp/idf/components/esp_ringbuf/include -I/opt/esp/idf/components/efuse/include -I/opt/esp/idf/components/efuse/esp32/include -I/opt/esp/idf/components/xtensa/include -I/opt/esp/idf/components/xtensa/esp32/include -I/opt/esp/idf/components/espcoredump/include -I/opt/esp/idf/components/espcoredump/include/port/xtensa -I/opt/esp/idf/components/esp_timer/include -I/opt/esp/idf/components/esp_ipc/include -I/opt/esp/idf/components/esp_pm/include -I/opt/esp/idf/components/vfs/include -I/opt/esp/idf/components/esp_wifi/include -I/opt/esp/idf/components/esp_wifi/esp32/include -I/opt/esp/idf/components/esp_event/include -I/opt/esp/idf/components/esp_netif/include -I/opt/esp/idf/components/esp_eth/include -I/opt/esp/idf/components/tcpip_adapter/include -I/opt/esp/idf/components/app_trace/include -I../components/audio_sal/include -I../components/audio_board/include -I../components/dsp_processor/include -I/opt/esp/idf/components/mbedtls/port/include -I/opt/esp/idf/components/mbedtls/mbedtls/include -I../components/esp_peripherals/driver/i2c_bus -mlongcalls -Wno-frame-address   -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -O2 -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v4.3.5\" -DESP_PLATFORM -DNDEBUG -MD -MT esp-idf/audio_hal/CMakeFiles/__idf_audio_hal.dir/driver/es8388/headphone_detect.c.obj -MF esp-idf/audio_hal/CMakeFiles/__idf_audio_hal.dir/driver/es8388/headphone_detect.c.obj.d -o esp-idf/audio_hal/CMakeFiles/__idf_audio_hal.dir/driver/es8388/headphone_detect.c.obj   -c ../components/audio_hal/driver/es8388/headphone_detect.c
../components/audio_hal/driver/es8388/headphone_detect.c:30:10: fatal error: board.h: No such file or directory
 #include "board.h"
          ^~~~~~~~~
compilation terminated.
[17/798] Building C object esp-idf/driver/CMakeFiles/__idf_driver.dir/spi_common.c.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
`

**Comment by CarlosDerSeher** [comment]
Sorry it isn't supported. It is not that hard to resolve and add support though. See https://github.com/CarlosDerSeher/snapclient/tree/master/components%2Faudio_board and copy your board from ESP ADF v2.1 (I think) to that location. Edit cmake file to do the code inclusions for your board. Maybe check kconfig file if someth needs to be uncommented. Check the lyrat v4.3 to see which parts of the code need to be commented to make it compile. Mostly the parts
