### ISSUE TITLE
I2S pin connection

### ISSUE THREAD

**Issue by TheHung184** [CarlosDerSeher/snapclient#7]
Hi, i am new to I2S and i have some UDA1334A board which i would like to try with your code. I have modifiedy the PCM5102A board to add to config and keep all I2S pin define for Master/Slave as default. My board is esp32-wemos-lolin32-lite
I have connect them as follow : 
        UDA1335a                      |                  ESP32 Lite
           WSEL                      --->>>            GPIO33 (mark as 33-pin13 ?)
           DIN                         --->>>            GPIO25 (mark as 25-pin14 ?)
           BCLK                       --->>>            GPIO0 (mark as 0-pin23 ?)
           MUTE                      --->>>            GPIO12 (mark as 12-pin18 ?)     
I havenot has any issue with compiling and detection of client but i cannot hear any sound from my DAC board. Can you share which pin connection you use ? Thank you
![image](https://user-images.githubusercontent.com/53043492/181150429-03eb3434-a785-4a88-8193-e2400f16995a.png)
![image](https://user-images.githubusercontent.com/53043492/181150492-cdeaaa1c-e632-41cb-9437-909b084ab1f0.png)

**Comment by majoreffort** [comment]
I think you are using the wrong pin numbering scheme. The correct numbers should be the ones labeled GPIOxx in the pinout picture and also the ones printed on the PCB, so for example connect BCLK --> GPIO23 if using the default pin configuration. 
Also, if you didn't modify the code, don't connect the mute GPIO, as the logic is inverted on the PCM5102A (low is mute).

**Comment by TheHung184** [comment]
> I think you are using the wrong pin numbering scheme. The correct numbers should be the ones labeled GPIOxx in the pinout picture and also the ones printed on the PCB, so for example connect BCLK --> GPIO23 if using the default pin configuration. Also, if you didn't modify the code, don't connect the mute GPIO, as the logic is inverted on the PCM5102A (low is mute).

I changed wiring as your suggestion and it worked. Thank you ^_^
