### ISSUE TITLE
MAX98357A volume

### ISSUE THREAD

**Issue by petanque** [CarlosDerSeher/snapclient#80]
I can't change the volume with MAX98357A, I've tried with and without software volume but it doesn't change.
Have I misunderstood something or am I doing it wrong?

**Comment by CarlosDerSeher** [comment]
I can only guess what you are doing... using the master? What are the logs? I think you need software volume control with this dac

**Comment by petanque** [comment]
Sorry for wasting your time.
I must have made a mistake, I deleted everything and started over and now it works.
Thank you

**Comment by petanque** [comment]
Sorry for wasting your time.
I must have made a mistake, I deleted everything and started over and now it works.
Thank you
